export const audioMap = {
  "Ms. Tan wrote down a messy list of numbers about her class's favourite fruits. It was hard to read! Then she turned it into a picture with bars. What could that picture be called?": "/assets/audio/ms_tan_wrote_down_a_messy_list_of_numbers_about_her_classs_favourite_fruits_it_was_hard_to_read_then_she_turned_it_into_a_picture_with_bars_what_could_that_picture_be_called_0.mp3",
  "It's a Bar Graph! Graphs and tables turn messy numbers into clear data we can read at a glance. Let's explore more in the story.": "/assets/audio/its_a_bar_graph_graphs_and_tables_turn_messy_numbers_into_clear_data_we_can_read_at_a_glance_lets_explore_more_in_the_story_1.mp3",
  "Ms. Tan asked her class about their favourite fruits, pets, reading habits, and the weather. She collected lots of numbers — but a long list is hard to read! Let's find out how to show information clearly.": "/assets/audio/ms_tan_asked_her_class_about_their_favourite_fruits_pets_reading_habits_and_the_weather_she_collected_lots_of_numbers_but_a_long_list_is_hard_to_read_lets_find_out_how_to_show_information_clearly_2.mp3",
  "A picture graph uses pictures or icons to show data. Each icon stands for a fixed number of items, shown in a key. Counting the apples, bananas, and oranges tells us exactly how many pupils liked each fruit!": "/assets/audio/a_picture_graph_uses_pictures_or_icons_to_show_data_each_icon_stands_for_a_fixed_number_of_items_shown_in_a_key_counting_the_apples_bananas_and_oranges_tells_us_exactly_how_many_pupils_liked_each_fruit_3.mp3",
  "A bar graph uses bars of different heights to show amounts. The taller the bar, the bigger the number! It has a scale on the side so we can read the exact value of each bar.": "/assets/audio/a_bar_graph_uses_bars_of_different_heights_to_show_amounts_the_taller_the_bar_the_bigger_the_number_it_has_a_scale_on_the_side_so_we_can_read_the_exact_value_of_each_bar_4.mp3",
  "A table organises numbers neatly into rows and columns — great for exact values. A line graph joins points with a line to show how something changes over time, like rising and falling temperatures across the week!": "/assets/audio/a_table_organises_numbers_neatly_into_rows_and_columns_great_for_exact_values_a_line_graph_joins_points_with_a_line_to_show_how_something_changes_over_time_like_rising_and_falling_temperatures_across_the_week_5.mp3",
  "Welcome to the Graph Explorer! Choose a data representation, and toggle highlights to find the total, highest, and lowest values.": "/assets/audio/welcome_to_the_graph_explorer_choose_a_data_representation_and_toggle_highlights_to_find_the_total_highest_and_lowest_values_6.mp3",
  "In the Data Counter, let's read the numbers. Tap the chart to explore, then use the number pad to fill in the grid.": "/assets/audio/in_the_data_counter_lets_read_the_numbers_tap_the_chart_to_explore_then_use_the_number_pad_to_fill_in_the_grid_7.mp3",
  "Let's match the descriptions on the left with the correct graph names on the right.": "/assets/audio/lets_match_the_descriptions_on_the_left_with_the_correct_graph_names_on_the_right_8.mp3",
  "Welcome to the Trend Sandbox. Tell me which features each graph type has, then click watch it to see why!": "/assets/audio/welcome_to_the_trend_sandbox_tell_me_which_features_each_graph_type_has_then_click_watch_it_to_see_why_9.mp3",
  "Excellent!": "/assets/audio/excellent_10.mp3",
  "Well done!": "/assets/audio/well_done_11.mp3",
  "Brilliant!": "/assets/audio/brilliant_12.mp3",
  "You got it!": "/assets/audio/you_got_it_13.mp3",
  "Super smart!": "/assets/audio/super_smart_14.mp3",
  "Not quite! Look at the hints and try again.": "/assets/audio/not_quite_look_at_the_hints_and_try_again_15.mp3",
  "Oh no! You have run out of hearts. Let's retry this world.": "/assets/audio/oh_no_you_have_run_out_of_hearts_lets_retry_this_world_16.mp3",
  "Tell me one way you could collect data about your classmates!": "/assets/audio/tell_me_one_way_you_could_collect_data_about_your_classmates_17.mp3",
  "What's your favourite way to show data — pictures, bars, tables, or lines?": "/assets/audio/whats_your_favourite_way_to_show_data_pictures_bars_tables_or_lines_18.mp3",
  "Can you name a graph type that uses a key?": "/assets/audio/can_you_name_a_graph_type_that_uses_a_key_19.mp3",
  "Where might you spot a bar graph or line graph in real life?": "/assets/audio/where_might_you_spot_a_bar_graph_or_line_graph_in_real_life_20.mp3",
  "What's the difference between a picture graph and a table?": "/assets/audio/whats_the_difference_between_a_picture_graph_and_a_table_21.mp3",
  "Time to reflect.": "/assets/audio/time_to_reflect_22.mp3",
  "Excellent reflection! Let's see your results.": "/assets/audio/excellent_reflection_lets_see_your_results_23.mp3"
};